// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/entry.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/ChatProvider.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/InputBox.tsx";
import * as $$3 from "./islands/WebSocket.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/entry.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/ChatProvider.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/InputBox.tsx": $$2,
    "./islands/WebSocket.ts": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
